export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const EVENTS_REQUEST = 'EVENTS_REQUEST';
export const EVENTS_SUCCESS = 'EVENTS_SUCCESS';
export const EVENTS_ERROR = 'EVENTS_ERROR';

export const EVENT_BY_ID_REQUEST = 'EVENT_BY_ID_REQUEST';
export const EVENT_BY_ID_SUCCESS = 'EVENT_BY_ID_SUCCESS';
export const EVENT_BY_ID_ERROR = 'EVENT_BY_ID_ERROR';

export const EVENT_DETAILS_REQUEST = 'EVENT_DETAILS_REQUEST';
export const EVENT_DETAILS_SUCCESS = 'EVENT_DETAILS_SUCCESS';
export const EVENT_DETAILS_ERROR = 'EVENT_DETAILS_ERROR';

export const EVENT_DETAILS_BY_ID_REQUEST = 'EVENT_DETAILS_BY_ID_REQUEST';
export const EVENT_DETAILS_BY_ID_SUCCESS = 'EVENT_DETAILS_BY_ID_SUCCESS';
export const EVENT_DETAILS_BY_ID_ERROR = 'EVENT_DETAILS_BY_ID_ERROR';

export const SAVE_EVENTS_REQUEST = 'SAVE_EVENTS_REQUEST';
export const SAVE_EVENTS_SUCCESS = 'SAVE_EVENTS_SUCCESS';
export const SAVE_EVENTS_ERROR = 'SAVE_EVENTS_ERROR';


export const EVENT_BOOKING_REQUEST = 'EVENT_BOOKING_REQUEST';
export const EVENT_BOOKING_SUCCESS = 'EVENT_BOOKING_SUCCESS';
export const EVENT_BOOKING_ERROR = 'EVENT_BOOKING_ERROR';


export const IMAGE_PATH = 'https://localhost:44306/EventImage/';